import { useEffect, useState, useMemo } from "react";
import VideoCard from "./VideoCard";
import { recordVideoView, unlockVideo, unlockVideoWithBasePay, getVideos } from "@/api/videos";
import { useBaseWallet } from "@/hooks/useBaseWallet";
import { useToast } from "@/hooks/use-toast";
import { useCategory } from "@/contexts/CategoryContext";
import { Interface, isAddress, getAddress } from "ethers";
import { addViewCredits } from "@/api/users";
import { discoverLocalVideos, generateVideoMetadata } from "@/utils/videoScanner";

const ERC20_ABI = [
  {
    type: 'function',
    name: 'transfer',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'to', type: 'address' },
      { name: 'value', type: 'uint256' }
    ],
    outputs: [{ name: 'success', type: 'bool' }]
  }
] as const;

const VideoFeed = () => {
  const [videos, setVideos] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const { isConnected, user: walletUser, address, sendGaslessTransaction, getCurrentNetwork, refreshUser } = useBaseWallet();
  const { toast } = useToast();
  const { selectedCategory } = useCategory();

  // Function to generate local video data from public/videos folder
  const generateLocalVideos = async () => {
    try {
      // Use the video scanner utility to discover local videos
      const discoveredVideos = await discoverLocalVideos();
      
      return discoveredVideos.map((video, index) => ({
        id: `local_${index + 1}`,
        title: video.title,
        topic: video.category,
        category: video.category,
        duration: video.duration,
        price: "Free",
        priceDisplay: "Free",
        tipAmount: 0,
        tipAmountDisplay: "0 USDC",
        thumbnail: "",
        locked: false,
        isFree: true,
        description: video.description,
        videoUrl: `/videos/${video.filename}`,
        totalViews: Math.floor(Math.random() * 200) + 50,
        playCount: Math.floor(Math.random() * 100) + 20
      }));
    } catch (error) {
      console.error('Error discovering local videos:', error);
      
      // Fallback to hardcoded list if scanning fails
      const fallbackVideos = [
        { filename: 'Ep1.mp4', title: 'Episode 1', category: 'Entertainment', duration: 25 },
        { filename: 'Eps2.mp4', title: 'Episode 2', category: 'Entertainment', duration: 30 },
        { filename: 'Vid3.mp4', title: 'Educational Video 3', category: 'Education', duration: 18 },
        { filename: 'Vid4.mp4', title: 'Educational Video 4', category: 'Education', duration: 22 },
        { filename: 'TestVideo.mp4', title: 'Test Video', category: 'General', duration: 15 }
      ];

      return fallbackVideos.map((video, index) => ({
        id: `local_${index + 1}`,
        title: video.title,
        topic: video.category,
        category: video.category,
        duration: video.duration,
        price: "Free",
        priceDisplay: "Free",
        tipAmount: 0,
        tipAmountDisplay: "0 USDC",
        thumbnail: "",
        locked: false,
        isFree: true,
        description: `Local video: ${video.title}`,
        videoUrl: `/videos/${video.filename}`,
        totalViews: Math.floor(Math.random() * 200) + 50,
        playCount: Math.floor(Math.random() * 100) + 20
      }));
    }
  };

  // Debug wallet state changes
  useEffect(() => {
    // Listen for credit purchase events from VideoCard components
    const handlePurchaseCredits = () => {
      purchaseCredits();
    };

    window.addEventListener('purchaseCredits', handlePurchaseCredits);
    return () => window.removeEventListener('purchaseCredits', handlePurchaseCredits);
  }, []);

  useEffect(() => {
    console.log('🔍 VideoFeed - Wallet state changed:', {
      isConnected,
      address,
      hasUser: !!walletUser,
      userCredits: walletUser?.viewCredits
    });
  }, [isConnected, address, walletUser]);
  // Handle credit update callback from VideoCard
  const handleCreditUpdate = async (remainingCredits: number) => {
    console.log('Credit updated to:', remainingCredits);
    
    // Immediately refresh user data to update UI
    await refreshUser();
    
    // Show toast notification about remaining credits
    if (remainingCredits === 0) {
      toast({
        title: 'No credits remaining',
        description: 'Purchase more credits to continue watching videos.',
        variant: 'destructive'
      });
    } else if (remainingCredits <= 3) {
      toast({
        title: `${remainingCredits} credits remaining`,
        description: 'Consider purchasing more credits soon.',
        variant: 'default'
      });
    }
  };

  const getVideoSrc = (video: any) => {
    const url = video.videoUrl || video.src;
    console.log('getVideoSrc called with:', { videoUrl: video.videoUrl, videoSrc: video.src, url });
    if (!url) {
      console.log('No URL found, returning empty string');
      return '';
    }
    // Support blob URLs generated by URL.createObjectURL for uploaded files
    if (url.startsWith('blob:')) {
      console.log('Found blob URL, returning as-is');
      return url;
    }
    if (/^https?:\/\//i.test(url)) {
      console.log('Found HTTP(S) URL, returning as-is');
      return url;
    }
    // For local videos, serve directly from public directory
    if (url.startsWith('/videos/')) {
      console.log('Found local video path, returning as-is');
      return url; // Already in correct format
    }
    const base = url.split('/').pop();
    if (!base) {
      console.log('Could not extract filename from URL');
      return '';
    }
    const finalUrl = `/videos/${base}`;
    console.log('Extracted filename and built local path:', finalUrl);
    return finalUrl;
  };

  useEffect(() => {
    const loadVideos = async () => {
      try {
        setLoading(true);
        
        // Try to fetch from API first
        const result = await getVideos({ limit: 20 });
        console.log('📺 API videos fetched:', result.data?.length || 0);
        
        if (result.success) {
          // Use API data even if empty array - don't fallback to local videos
          setVideos(result.data || []);
          console.log('✅ Using API videos (including empty results)');
        } else {
          // Only fallback to local videos if API call failed (not success)
          console.log('📁 API call failed, falling back to local videos...');
          const localVideos = await generateLocalVideos();
          console.log('📁 Local videos loaded:', localVideos.length);
          setVideos(localVideos);
        }
      } catch (error) {
        console.error('Error loading videos:', error);
        // Fallback to local videos on error
        console.log('📁 Error fallback to local videos...');
        const localVideos = await generateLocalVideos();
        setVideos(localVideos);
      } finally {
        setLoading(false);
      }
    };

    loadVideos();
  }, []);

  const filteredVideos = useMemo(() => {
    if (selectedCategory === 'all') {
      return videos;
    }
    return videos.filter(video => video.category === selectedCategory);
  }, [videos, selectedCategory]);

  const purchaseCredits = async () => {
    try {
      if (!isConnected || !address) {
        toast({ title: 'Wallet not connected', description: 'Connect your wallet to purchase credits.' });
        return;
      }

      console.log('🛒 Starting credit purchase process...');

      const network = getCurrentNetwork();
      const env = (import.meta as any).env ?? {};
      const sanitize = (s?: string) => {
        let t = (s ?? '').normalize();
        t = t.replace(/['"\u200B-\u200D\uFEFF\s]/g, '').trim();
        const m = t.match(/0x[0-9a-fA-F]{40}/);
        return (m ? m[0] : t).toLowerCase();
      };
      const receiverRaw = env.VITE_CREDITS_RECEIVER_ADDRESS as string | undefined;
      const usdcMainnetRaw = env.VITE_USDC_MAINNET_ADDRESS as string | undefined;
      const usdcTestnetRaw = env.VITE_USDC_TESTNET_ADDRESS as string | undefined;

      const receiverTrimmed = sanitize(receiverRaw);
      if (!receiverTrimmed) {
        toast({ title: 'Receiver not configured', description: 'Set VITE_CREDITS_RECEIVER_ADDRESS in your environment.' });
        return;
      }
      if (!isAddress(receiverTrimmed)) {
        toast({ title: 'Invalid receiver address', description: 'VITE_CREDITS_RECEIVER_ADDRESS must be a valid EVM address.' });
        console.error('❌ Invalid receiver address:', receiverTrimmed);
        return;
      }
      let receiver: `0x${string}`;
      try {
        receiver = getAddress(receiverTrimmed) as `0x${string}`;
      } catch (e) {
        console.error('❌ Failed to checksum receiver address:', receiverTrimmed, e);
        toast({ title: 'Invalid receiver address', description: 'Receiver address could not be parsed.' });
        return;
      }

      const usdcMainnetTrimmed = sanitize(usdcMainnetRaw);
      const usdcTestnetTrimmed = sanitize(usdcTestnetRaw);

      const isTestnet = Boolean(network?.isTestnet) || String(network?.chainId) === '84532' || String(network?.name || '').toLowerCase().includes('sepolia');
      const usdcAddressRaw = isTestnet ? usdcTestnetTrimmed : usdcMainnetTrimmed;
      if (!usdcAddressRaw) {
        toast({ title: 'USDC address missing', description: 'Set USDC contract address env for current network.' });
        return;
      }
      if (!isAddress(usdcAddressRaw)) {
        toast({ title: 'Invalid USDC address', description: 'USDC contract address must be a valid EVM address.' });
        console.error('❌ Invalid USDC contract address:', usdcAddressRaw);
        return;
      }
      let usdcAddress: `0x${string}`;
      try {
        usdcAddress = getAddress(usdcAddressRaw) as `0x${string}`;
      } catch (e) {
        console.error('❌ Failed to checksum USDC address:', usdcAddressRaw, e);
        toast({ title: 'Invalid USDC address', description: 'USDC address could not be parsed.' });
        return;
      }

      // 1 USDC with 6 decimals
      const amount = 1_000_000n;
      const iface = new Interface(ERC20_ABI);
      const data = iface.encodeFunctionData('transfer', [receiver, amount]);

      console.log('💸 Sending USDC transaction...', { to: usdcAddress, amount: amount.toString() });
      const txHash = await sendGaslessTransaction(usdcAddress, data, '0x0');
      console.log('✅ Transaction successful:', txHash);

      // After successful onchain payment, grant 10 credits
      console.log('🎯 Adding credits to user account...');
      const res = await addViewCredits(address, 10);

      if (res?.success) {
        console.log('✅ Credits added successfully:', res.data);
        toast({
          title: 'Credits purchased',
          description: `You now have ${res.data?.viewCredits || 'more'} view credits.`
        });
        await refreshUser();
      } else {
        console.error('❌ Credit update failed:', res);
        toast({
          title: 'Credits update failed',
          description: res?.error || 'Transaction succeeded but credit update failed. Please contact support.'
        });

        // Log transaction details for debugging
        console.error('Transaction succeeded but credit update failed:', {
          txHash,
          walletAddress: address,
          creditsToAdd: 10,
          apiResponse: res
        });
      }
    } catch (e: any) {
      console.error('❌ Error purchasing credits:', e);
      const detail = e?.data?.message || e?.details || e?.message || 'Transaction could not be sent.';
      const isNetworkIssue = typeof detail === 'string' && detail.toLowerCase().includes('wrong network');
      toast({
        title: isNetworkIssue ? 'Wrong network' : (detail.toLowerCase().includes('transaction') ? 'Transaction failed' : 'Purchase failed'),
        description: isNetworkIssue ? 'Please switch to the expected Base network and try again.' : detail
      });
    }
  };

  // Handle video unlock with payment method selection
  const handleVideoUnlock = async (videoId: string, paymentMethod: 'crypto' | 'basepay' | 'bulk', transactionHash?: string) => {
    if (!isConnected || !walletUser?._id) {
      toast({
        title: "Wallet Not Connected",
        description: "Please connect your wallet to unlock videos",
        variant: "destructive",
      });
      return;
    }

    try {
      // Use actual transaction hash if provided, otherwise generate mock for testing
      const finalTransactionHash = transactionHash || `0x${Math.random().toString(16).substr(2, 64)}`;

      // Call the new video unlock API endpoint
      const response = await fetch('/api/video-unlock', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          userId: walletUser._id,
          videoId: videoId,
          transactionHash: finalTransactionHash,
          paymentMethod: paymentMethod,
          amount: 100000, // 0.1 USDC in wei
          amountDisplay: "0.1 USDC"
        })
      });

      const result = await response.json();

      if (result?.success) {
        toast({
          title: "Video Unlocked!",
          description: `Successfully unlocked with ${paymentMethod === 'basepay' ? 'BasePay' : 'regular payment'}`,
        });

        // Refresh user data to update unlocked videos
        await refreshUser();

        // Refresh videos to show unlocked status
        refetchVideos();
      } else {
        throw new Error(result?.error || 'Failed to unlock video');
      }
    } catch (error) {
      console.error('Error unlocking video:', error);
      toast({
        title: "Unlock Failed",
        description: error instanceof Error ? error.message : "Failed to unlock video",
        variant: "destructive",
      });
    }
  };



  // Function to refetch videos after unlock
  const refetchVideos = async () => {
    try {
      const result = await getVideos({ limit: 20 });
      if (result.success) {
        setVideos(result.data);
      }
    } catch (error) {
      console.error('Error refetching videos:', error);
    }
  };

  // Handle video click
  const handleVideoClick = async (videoId: number) => {
    console.log(`handleVideoClick called for video ${videoId}`);
    try {
      if (isConnected && walletUser?._id) {
        const result = await recordVideoView(videoId.toString(), walletUser._id);
        // Refresh user data to update view credits in real-time
        if (result?.success) {
          await refreshUser();
        }
      }
      // Video play action - removed console.log for production
    } catch (e) {
      console.error('Error playing video:', e);
    }
  };

  if (loading) {
    return (
      <section className="py-12">
        <div className="container mx-auto px-4">
          <div className="flex items-center justify-between mb-8">
            <h2 className="text-2xl font-bold">
              Latest <span className="text-gradient">Drops</span>
            </h2>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
            {[...Array(10)].map((_, i) => (
              <div key={i} className="animate-pulse bg-gray-200 rounded-lg h-48"></div>
            ))}
          </div>
        </div>
      </section>
    );
  }

  return (
    <section className="py-12" aria-label="Latest Drops">
      <div className="container mx-auto px-4">
        <div className="flex items-center justify-between mb-8">
          <h2 className="text-2xl font-bold">
            Latest <span className="text-gradient">Drops</span>
          </h2>
          <div className="flex items-center gap-4" />
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
          {filteredVideos.map((video) => {
            const id = video._id || video.id;

            // Check if user has unlocked this video
            const isVideoUnlocked = walletUser?.videosUnlocked?.includes(id.toString()) || false;

            // Determine if video should be locked
            // Videos are locked if:
            // 1. Video is not free AND
            // 2. User hasn't unlocked it AND
            // 3. (Wallet is not connected OR User has no view credits)
            const finalIsLocked = !video.isFree && !isVideoUnlocked && (!isConnected || (walletUser?.viewCredits ?? 0) === 0);

            const videoPrice = video.price || 100000; // Default 0.1 USDC in wei
            const videoPriceDisplay = video.priceDisplay || "0.1 USDC";

            console.log('Rendering VideoCard:', {
              id,
              title: video.title,
              videoUrl: video.videoUrl,
              src: getVideoSrc(video),
              isLocked: finalIsLocked,
              hasCredits: walletUser?.viewCredits > 0
            });

            return (
              <VideoCard
                key={`video-${id}`}
                title={video.title}
                topic={video.topic}
                duration={video.duration}
                thumbnail={video.thumbnail}
                description={video.description}
                src={getVideoSrc(video)}
                price={video.priceDisplay}
                isLocked={finalIsLocked}
                isFree={video.isFree}
                videoId={video.id?.toString() || id.toString()}
                totalViews={video.totalViews}
                playCount={video.playCount}
                creatorWallet={video.creatorWallet}
                totalTipsEarned={video.totalTipsEarned}
                showTipButton={true}
                onCreditUpdate={handleCreditUpdate}
                onUnlock={(paymentMethod, transactionHash) => handleVideoUnlock(video.id?.toString() || id.toString(), paymentMethod, transactionHash)}
                onClick={() => {
                  console.log(`Video ${video.id || id} clicked - locked: ${finalIsLocked}, hasCredits: ${walletUser?.viewCredits > 0}, isFree: ${video.isFree}`);
                  handleVideoClick(video.id || id);
                }}
              />
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default VideoFeed;
